"""The menu charset: the game's font at the same codes (texts work on both
charsets), then the CPC's logo (gfx/png/logo_cpc.png, 144 x 48 mode 0 pixels
= 36 x 6 multicolor cells) from code LOGO_FIRST on.

Colours: background black, MC1 blue (the letters' shadow), MC2 orange on the
logo's rows 0-2 (RUNNER) and grey on rows 3-5 (A.P.E.R, the rails): the menu
IRQ changes $D023 between them (src/screens.asm). Each cell gets the most
used of its other colours (0-7, colour RAM); a pixel of yet another colour
takes the nearest of the cell's four.

Outputs src/data/menu_charset.bin (2 KB) and src/data/logo.asm (logo_chars,
logo_colours: 6 rows x 36, row by row; LOGO_* constants).
"""

import os
import sys

from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from c64palette import RGB, colour  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SRC = os.path.join(ROOT, "gfx", "png", "logo_cpc.png")
DATA = os.path.join(ROOT, "src", "data")
FONT_CHARS = 57                       # codes 0-56 of the game charset (png2c64)
LOGO_FIRST = FONT_CHARS
W, H = 36, 6
BG, MC1 = colour("black"), colour("blue")
MC2_ROWS = [colour("orange")] * 3 + [colour("grey")] * 3

# the CPC logo's colours -> C64 colours
CPC_TO_C64 = {
    (0, 0, 0): colour("black"), (0, 0, 128): colour("blue"), (255, 255, 0): colour("yellow"),
    (128, 0, 0): colour("red"), (255, 128, 0): colour("orange"), (255, 0, 0): colour("red"),
    (255, 255, 255): colour("white"), (0, 128, 0): colour("green"), (128, 128, 128): colour("grey"),
}


def dist(a, b):
    return sum((x - y) ** 2 for x, y in zip(RGB[a], RGB[b]))


def convert():
    im = Image.open(SRC).convert("RGB")
    assert im.size == (W * 4, H * 8), im.size
    px = [[CPC_TO_C64[im.getpixel((x, y))] for x in range(W * 4)] for y in range(H * 8)]
    font = open(os.path.join(DATA, "charset.bin"), "rb").read()[:FONT_CHARS * 8]
    chars = [font[i * 8:i * 8 + 8] for i in range(FONT_CHARS)]
    index = {c: i for i, c in enumerate(chars)}
    codes, colours, lost = [], [], 0
    for cy in range(H):
        mc2 = MC2_ROWS[cy]
        for cx in range(W):
            cell = [row[cx * 4:cx * 4 + 4] for row in px[cy * 8:cy * 8 + 8]]
            counts = {}
            for row in cell:
                for c in row:
                    if c not in (BG, MC1, mc2):
                        counts[c] = counts.get(c, 0) + 1
            own = max((c for c in counts if c < 8), key=counts.get, default=colour("white"))
            pens = (BG, MC1, mc2, own)
            data = bytearray()
            for row in cell:
                b = 0
                for c in row:
                    bits = min(range(4), key=lambda k: dist(pens[k], c))
                    lost += pens[bits] != c
                    b = b << 2 | bits
                data.append(b)
            data = bytes(data)
            if data not in index:
                index[data] = len(chars)
                chars.append(data)
            codes.append(index[data])
            colours.append(8 | own)
    if len(chars) > 256:
        raise SystemExit(f"mklogo64: {len(chars)} characters > 256")
    # the MC2 change between rows 2 and 3: no MC2 on the lines around it
    for y in (2 * 8 + 7, 3 * 8):
        assert not any(c == MC2_ROWS[y // 8] for c in px[y]), f"MC2 on logo line {y}"
    return chars, codes, colours, lost


def main():
    chars, codes, colours, lost = convert()
    with open(os.path.join(DATA, "menu_charset.bin"), "wb") as f:
        f.write(b"".join(chars).ljust(2048, b"\0"))
    lines = ["; generated by tools/mklogo64.py from gfx/png/logo_cpc.png - do not edit",
             f"LOGO_W = {W}", f"LOGO_H = {H}", f"LOGO_MC1 = {MC1}",
             f"LOGO_MC2_TOP = {MC2_ROWS[0]}", f"LOGO_MC2_BOTTOM = {MC2_ROWS[-1]}",
             "logo_chars"]
    for r in range(H):
        lines.append("        .byte " + ", ".join(str(c) for c in codes[r * W:(r + 1) * W]))
    lines.append("logo_colours")
    for r in range(H):
        lines.append("        .byte " + ", ".join(str(c) for c in colours[r * W:(r + 1) * W]))
    with open(os.path.join(DATA, "logo.asm"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"mklogo64: {len(chars)} menu characters ({len(chars) - FONT_CHARS} logo), {lost} pixels recoloured")


if __name__ == "__main__":
    main()
