"""Compiles the screen texts (text/<language>.txt, the CPC's) into font codes.

Every language file has the same names in the same order. Each "name: text"
becomes a string of font codes (assets64.FONT_GLYPHS: the code of a glyph is
its index) ending in TEXT_END. src/data/text.asm: text_lo / text_hi, a
pointer per text, language after language (index + language * TXT_COUNT),
and TXT_<NAME> = the text's index. Accents are dropped: capitals only.
"""

import os
import sys
import unicodedata

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import assets64 as A  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
LANGUAGES = ("en", "el")
TEXT_DIR = os.path.join(ROOT, "text")
OUT = os.path.join(ROOT, "src", "data", "text.asm")
END = 0xFF

GLYPH = {ch: i for i, (_, chars) in enumerate(A.FONT_GLYPHS) for ch in chars}


class TextError(Exception):
    pass


def glyphs(text, where=""):
    out = []
    for ch in unicodedata.normalize("NFD", text):
        if unicodedata.combining(ch):
            continue
        if ch not in GLYPH:
            raise TextError(f"{where}: no glyph for {ch!r} in {text!r}")
        out.append(GLYPH[ch])
    return out


def load(path):
    texts = {}
    with open(path, encoding="utf-8") as f:
        for number, line in enumerate(f, 1):
            line = line.rstrip("\n")
            if not line.strip() or line.startswith("#"):
                continue
            name, sep, text = line.partition(":")
            if not sep or not name.strip().isidentifier():
                raise TextError(f"{path}:{number}: expected 'name: text'")
            texts[name.strip()] = glyphs(text.strip(), f"{path}:{number}")
    return texts


def load_all():
    languages = {lang: load(os.path.join(TEXT_DIR, f"{lang}.txt")) for lang in LANGUAGES}
    names = list(languages[LANGUAGES[0]])
    for lang, texts in languages.items():
        if list(texts) != names:
            missing = set(names) ^ set(texts)
            raise TextError(f"text/{lang}.txt: names differ from text/{LANGUAGES[0]}.txt"
                            f" ({', '.join(sorted(missing)) or 'order'})")
    return languages


def main():
    try:
        languages = load_all()
    except TextError as e:
        print(f"mktext64: {e}", file=sys.stderr)
        return 1
    names = list(languages[LANGUAGES[0]])
    labels = [f"text_{lang}_{name}" for lang in LANGUAGES for name in names]
    lines = ["; generated by tools/mktext64.py from text/*.txt - do not edit",
             f"TEXT_END = ${END:02x}", f"TXT_COUNT = {len(names)}", f"LANGUAGES = {len(LANGUAGES)}"]
    lines += [f"TXT_{name.upper()} = {i}" for i, name in enumerate(names)]
    lines += ["text_lo", "        .byte " + ", ".join(f"<{l}" for l in labels),
              "text_hi", "        .byte " + ", ".join(f">{l}" for l in labels)]
    for lang, texts in languages.items():
        for name, codes in texts.items():
            lines.append(f"text_{lang}_{name} .byte " + ", ".join(str(c) for c in codes + [END]))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"mktext64: {len(names)} texts x {len(LANGUAGES)} languages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
